"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN

"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files":
  [
    {
      "source": "src/modules/localization/locales/en-US/*.json",
      "translation": "src/modules/localization/locales/%two_letters_code%/%original_file_name%",
      "languages_mapping": { "two_letters_code": { "pt": "pt-BR" } },
    },
  ]
