name: Crowdin export

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  crowdin-export:
    name: download translations
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1 # Should be 1 to avoid parallel builds
      matrix:
        lc: [pt-PT, ro] # https://developer.crowdin.com/language-codes/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Matrix
        uses: crowdin/github-action@1.5.2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          download_language: ${{ matrix.lc }}
          localization_branch_name: l10n_${{ matrix.lc }}

          create_pull_request: true
          commit_message: "feat(l10n): add `${{ matrix.lc }}` translation"
          pull_request_title: "feat(l10n): add ${{ matrix.lc }} translations"
          pull_request_body: "PR adding translation string(s) for the following locale: `${{ matrix.lc }}`"
          pull_request_base_branch_name: stable
          pull_request_labels: "l10n"
          pull_request_assignees: "cuaies"
          pull_request_reviewers: "cuaies"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
