name: Label sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/labels.yml"

jobs:
  label-sync:
    name: label sync
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: label sync
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
